//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Type { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string ObsInd { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
