//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizAnswer
    {
        public int QuizAnswerID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> ChoiceSelected { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ObsInd { get; set; }
    
        public virtual QuizChoice QuizChoice { get; set; }
        public virtual QuizQuestion QuizQuestion { get; set; }
        public virtual User User { get; set; }
    }
}
